repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c "cd stockvaluefinder && uv run python -m mypy ."
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-check
        name: ruff check
        entry: bash -c "cd stockvaluefinder && uv run ruff check ."
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: ruff format
        entry: bash -c "cd stockvaluefinder && uv run ruff format ."
        language: system
        pass_filenames: false
        always_run: true
